### ISSUE TITLE
PCAWG cohort selection not producing io targets (or any) plots

### ISSUE THREAD

**Issue by Gibbsdavidl** [CRI-iAtlas/iatlas-app#132]
After making a cohort selection with PCAWG, I can't make io targets plots (or any plots).

<img width="893" alt="cohort1" src="https://user-images.githubusercontent.com/561865/144507583-aed24cf5-e0c9-49c9-b129-b82de4bf2d4e.PNG">

<img width="885" alt="cohort2" src="https://user-images.githubusercontent.com/561865/144507588-d032716f-66c3-455e-924c-0082af6db11f.PNG">

**Comment by andrewelamb** [comment]
@Gibbsdavidl This looks like an issue with using immune feature bins as a group. I'll look into it.
