### ISSUE TITLE
Cohort Selection, Select All Groups 

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#133]
Is it possible to include a 'select all' or 'unselect all' in the group selection menu (and similar selection menus)
![image](https://user-images.githubusercontent.com/2837859/144653577-f55de728-0502-481e-9fa1-a3f47754a99b.png)

**Comment by vthorsson** [comment]
PS Maybe not worth getting into if it is difficult to implement.  Would typically only be used with large numbers of available groups.

**Comment by andrewelamb** [comment]
@vthorsson I don't think it would be too hard to add. I'll prioritize it under bugs, but will see if I can get to it before the release.
