### ISSUE TITLE
Cohort selection - unexpected cohort and grouping behavior

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#134]
Selected a few TCGA studies, then TCGA study as grouping variable.  Got immunomodulator plot with all TCGA studies.

![image](https://user-images.githubusercontent.com/2837859/144654522-fb7c12c7-0d9d-46ce-817f-b7fc7f3d2776.png)
![image](https://user-images.githubusercontent.com/2837859/144654631-2ee6abff-6549-43b0-b5f6-f15c09818e25.png)

**Comment by andrewelamb** [comment]
@vthorsson I can't reproduce this bug, in shinyapps.io, or locally.

**Comment by vthorsson** [comment]
Agreed @andrewelamb , not showing up now , will close.
