### ISSUE TITLE
Cohort selection - binning of Immune feature not carried to other modules 

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#137]
Binning of e.g. Age at Diagnosis is not carried through to plot, e.g Immunomodulators
![image](https://user-images.githubusercontent.com/2837859/144663890-170a1586-1d98-4b8f-a466-b353ad2c9e97.png)
![image](https://user-images.githubusercontent.com/2837859/144664155-1c8afc96-2425-4075-a888-3f58cc4de45f.png)
Possibly related: each bin has the same name, at least as displayed in the table

**Comment by andrewelamb** [comment]
@vthorsson I think this is the same as #132

**Comment by vthorsson** [comment]
> @vthorsson I think this is the same as #132

Does indeed seem to be , @andrewelamb
