### ISSUE TITLE
Cohort selection - missing the instructions file for cohort upload

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#138]
App crashes when user clicks formatting instructions for the user-specified groups, possibly due to a not being able to access a needed file

![image](https://user-images.githubusercontent.com/2837859/144667479-6edc639a-5dfc-428e-97af-cb20562a1bad.png)

![image](https://user-images.githubusercontent.com/2837859/144667969-35d91b3c-02f2-4d5f-b21e-9af1a9084dc9.png)

![image](https://user-images.githubusercontent.com/2837859/144668111-732fd1ca-49e6-4563-b509-e9b306e4b275.png)

**Comment by vthorsson** [comment]
Maybe needs to draw from `iatlas-app/inst/markdown/user_groups.markdown`  . However , that file may also need to be updated as it references `shiny-iatlas`

**Comment by andrewelamb** [comment]
Hmm it may not have been moved from the old repo. I'll look into it.

**Comment by vthorsson** [comment]
This is error is also happening  in  the ICI cohort selection module
