### ISSUE TITLE
Restore functionality for user-defined sample groups 

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#139]
Restore  where possible the functionality of analyses following upload of user-specified sample groups. E.g for `iatlas-app/inst/examples/example_user_group2.csv` initial upload seems to succeed but groups are not carried forward for analysis or use in other apps, such as the immumodulators or IO targets (focusing on the less complex modules)

**Comment by vthorsson** [comment]
During read-in , a warning is reported on the example file
```
Column `short_name` doesn't exist
```
perhaps that is affecting subsequent steps

**Comment by andrewelamb** [comment]
Yep it looks like something broke at some point.
