### ISSUE TITLE
Allow download of summary information from plots when applicable

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#14]
From a summary barchart allow download e.g. the means and std devs as a tsv file.  Same for similar instances of summary information shown in other plots.

**Comment by andrewelamb** [comment]
@vthorsson I think this is completed? I think I've added the ability to download the data that went into each plot. Can you check?

**Comment by vthorsson** [comment]
Agreed that it is completed @andrewelamb . Checked on immunomodulator violin plot on public app.

**Comment by vthorsson** [comment]
@andrewelamb , I noticed the following difference, with the Immunomodulator example

current testing app  https://isb-cgc.shinyapps.io/iatlas-v2-staging/
Downloaded file
x,y
C4,1.203598516335235
C4,2.733643371826536
C4,0.47057218190538247
C4,1.3767502753074006
C4,2.040428271015897
etc.

Public app
x,y,label
C4,2.0356978372618983,TCGA-02-2485
C3,2.3131434962893227,TCGA-05-4410
etc

Thus data download does indeed happen in both cases, But is it possible that the TCGA IDs are not included in what is sent to plotly, in the newer plots?

**Comment by andrewelamb** [comment]
@vthorsson That's likely, I didn't have the download file sin mind when redoing a lot of the code. I'll add them back in.

**Comment by andrewelamb** [comment]
@vthorsson This and the io targets plots have been fixed, and pushed to staging.

**Comment by andrewelamb** [comment]
@vthorsson Let me know if there are any other plot downloads that you'd like me to update otherwise I'll go ahead and re close this.

**Comment by vthorsson** [comment]
Thanks @andrewelamb for getting that in.  As regards plot download checks - it might require a pass through all of them with this check in mind. Perhaps that can be added as a separate issue?

**Comment by andrewelamb** [comment]
@vthorsson Either way is fine with me.
