### ISSUE TITLE
Error in extracellular network with selection of gene cohort "Extracellular Network Genes"

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlas-app#141]
The selection of Immunomodulator Genes or individual genes are ok, problem only with Extracellular Network Genes:

![image](https://user-images.githubusercontent.com/32350126/144677701-7a1da643-0c10-4d65-a2f0-97402274dbbd.png)

**Comment by andrewelamb** [comment]
@heimannch This seems to be a Gateway Timeout (HTTP 504) error, at least locally. I think that means the query is failing due to memory issues. I'll see about getting that fixed.
