### ISSUE TITLE
Cell Interaction Diagram not working with PCAWG

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#142]
With the default PCAWG cohort and default sample groups: Immune Subtype, no cell interaction diagram is generated 

![image](https://user-images.githubusercontent.com/2837859/144678262-23807889-abb1-4a3f-a3a1-00a6161729fc.png)

**Comment by heimannch** [comment]
Same behavior observed in Extracellular Networks module.
