### ISSUE TITLE
Updates to Explore page

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlas-app#145]
Left menu:
- [x] append "CG" to Cohort Selection and Analysis Modules
- [x] change ICI Modules to ICI Analysis Modules
- [x] move Data Description to the bottom of the left menu

Main panel:
- [x] update initial text with instructions to visit Cohort Selection
- [x] update "What's inside" with PCAWG and ICI data
- [x] add link to manuscript in text below "Analysis Modules" https://www.cell.com/immunity/abstract/S1074-7613(18)30121-3
- [x] add section with ICI modules 
- [x] add the CG and ICI references in each of the main sections of analysis modules

**Comment by heimannch** [comment]
Some suggestions from dev meeting:

- [ ] More indentation to show nesting of viz in the two different modules
- [ ] Have a tumor type as part of “what’s inside?”
- [x] Reorder so that ICI modules come first
- [ ] Consistent name across “Portal” vs “Explore” vs “Explorer” (@ychae to check comments from colleagues)

**Comment by andrewelamb** [comment]
@heimannch What's the reasoning behind "Reorder so that ICI modules come first"?

**Comment by heimannch** [comment]
(Just to make sure it's registered here, I will use what Vésteinn wrote on Slack)
"Was suggested and followed up on as the ICI data is probably considered more new and exciting by the community"

This change is still up to discussion, so feel free to share any opinions you might have about it!
