### ISSUE TITLE
Data Description in 2.0 missing Variable Type column

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlas-app#155]
The Variable Type column in Data Description is not present in the 2.0 version.
I imagine that this information is not encoded anymore in tables in the database, as numeric variables are in the features table and categorical in the tags table. Do we want/need to add them again to Data Description?

**Comment by andrewelamb** [comment]
@heimannch You are correct about that being redundant in the database.

I personally don't think it's a very useful column.

**Comment by heimannch** [comment]
@vthorsson, do you have any thoughts on this?

**Comment by vthorsson** [comment]
@andrewelamb  I find that the "Variable Type" column adds useful information to people . 

However if it no longer easy to access for display, or a chore to re-introduce it would not be a high priority item to get it in.
