### ISSUE TITLE
Group together "What's inside" metrics

### ISSUE THREAD

**Issue by tschaffter** [CRI-iAtlas/iatlas-app#165]
The layout of the section "What's inside" looks like this on a 4K display:

![image](https://user-images.githubusercontent.com/3056480/147007274-ae579114-bc99-44fa-b3ae-5ab584089c59.png)

After reducing the width of my browser window by a bit, the layout looks a bit better to me with the metrics grouped on the right side.

![image](https://user-images.githubusercontent.com/3056480/147007386-f0494266-22f4-4641-8e77-bb09680c5b34.png)

## Suggestion

- Group the metrics by default to the right side as show on the second screenshot

**Comment by andrewelamb** [comment]
@heimannch I was thinking we fixed this. Was the staging up updated with this fix?

**Comment by heimannch** [comment]
Yes, it's fixed! I will redeploy the app to make sure the fix is included in the web app.
