### ISSUE TITLE
Dataset Overview > Category Key > Incomplete Order values for Race category

### ISSUE THREAD

**Issue by tschaffter** [CRI-iAtlas/iatlas-app#167]
The column "Order" in the table is missing values when selecting Race. This seems to be an odd case as most of the other category I selected have a full column "Order" with value sorted in ascending order. I haven't tried all category values.

![image](https://user-images.githubusercontent.com/3056480/147008525-7380e478-cbd1-4606-8786-857df37fe659.png)

**Comment by andrewelamb** [comment]
@heimannch Could you comment on what the order is here? I know some classes of features have an order for plotting purposes, such as Cibersort results. Did we start adding order to groups such as gender and race at some point?

**Comment by heimannch** [comment]
I did, for the ICI tags. The main reason to do that was that we have several categories that are ordered (eg. response annotation with levels that ranges from Complete Response -> Progressive Disease) and the plots should follow this order. I think in the case in the screenshot, the order didn't propagate to tags that were already present in the CG datasets.

**Comment by andrewelamb** [comment]
Should we assign orders to tags where some on the group have an order and some don't? I think only the ICI modules 
make use of tag order.

**Comment by heimannch** [comment]
Yeah, that's a good solution. I imagine that this issue will be present with other categories that are present in TCGA and PCAWG, and in the ICI datasets have an extra level of "other"/"not available"/ "unknown" that would look best in the last rows of this table.

**Comment by andrewelamb** [comment]
Ok I'm not going to assign this to the 2.0 milestone since it's not pressing. We can return to it after we release 2.0.
