### ISSUE TITLE
Machine Learning > Unable to find where the logs are

### ISSUE THREAD

**Issue by tschaffter** [CRI-iAtlas/iatlas-app#168]
The error appeared when I clicked on `Train Model`.

![image](https://user-images.githubusercontent.com/3056480/147009092-ad5759c8-8d68-4b6b-9089-b8d3e51e08ac.png)

**Comment by heimannch** [comment]
Thanks, @tschaffter ! Users are not supposed to see logs, this error should have been caught earlier. Can you confirm that your selection of "Gide 2019" as training dataset yields, in the light gray box below the main selection, a count of "Samples in training set: 0"? Did you add any filters to your cohort in the ICI Cohort Selection?

**Comment by tschaffter** [comment]
> Can you confirm that your selection of "Gide 2019" as training dataset yields, in the light gray box below the main selection, a count of "Samples in training set: 0"?

Yes

> Did you add any filters to your cohort in the ICI Cohort Selection?

The screenshot shows the options I have selected at the time of the error before clicking on `Train model`
