### ISSUE TITLE
Machine Learning > Set initial configuration so that the user can just click on `Train model`

### ISSUE THREAD

**Issue by tschaffter** [CRI-iAtlas/iatlas-app#169]
I played a bit with the section `Machine Learning` but couldn't get a model to train.

When arriving on the page, the button `Train model` is not disabled. Clicking on it does not produce any response from the app. Consider disabling the button until all required field as set.

Alternatively, populate automatically all the field with an initial configuration that allows the user to click on `Train models` right after landing on this page.

**Comment by heimannch** [comment]
Hi @tschaffter, thanks so much for your report about your attempts to use the `Machine Learning` module! The live version now has some extra directions and controls that should make things clearer. Hope you have the chance to take a look at it again, and please let us know if you have any other comments or suggestions!

**Comment by tschaffter** [comment]
The additional info helps. This time I was able to successfully train a model. Thanks!
