### ISSUE TITLE
Residual references to shiny-iatlas

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#177]
There are instances where (the earlier repo) `shiny-iatlas` is referenced.  Check if that should be so or if they should be transitioned to refs in `iatlas-app` repo.

Examples can be seen by search, as in the image here.  For Documentation page, after editing `iatlas-app/inst/markdown/docs.markdown`, check that the referenced documentation is indeed from `iatlas-app` and not `shiny-iatlas`

![image](https://user-images.githubusercontent.com/2837859/148436967-78db806a-2228-4f1d-ae93-f8052558706b.png)

**Comment by heimannch** [comment]
@andrewelamb, the last item in the screenshot above is references to `markdown/user_groups.markdown`, but it looks like this file is not being called anywhere in the app - do you plan on including it somewhere, or should we delete it?

**Comment by andrewelamb** [comment]
@heimannch Yes this should have been deleted at some point. (The real version lives in https://github.com/CRI-iAtlas/iatlas.modules2)
