### ISSUE TITLE
Discrete palette in ICI modules not colorblind friendly

### ISSUE THREAD

**Issue by jaeddy** [CRI-iAtlas/iatlas-app#179]
Many of the ICI module charts use red and green as the primary colors to distinguish groups.

![image](https://user-images.githubusercontent.com/5033229/149218299-be0492f5-7b84-4009-b00c-bcd0724176c1.png)

I would recommend something like the colorblind palette from [`ggthemes`](https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/)

![image](https://user-images.githubusercontent.com/5033229/149219140-a00fe803-3bc9-4007-88c2-033d614aa6b3.png)

**Comment by heimannch** [comment]
@jaeddy, thanks for bringing that up. I checked the tool used to generate the palettes, and most of them are already colorblind friendly. The ones associated with response to treatment were cherry picked, but now were updated with colorblind friendly colors.

@andrewelamb, I updated the tags file on Synapse with the new colors, so next time the database is updated the colors will be updated in the portal.

**Comment by andrewelamb** [comment]
@heimannch The tags table isn't building with the changes. I'm getting this error now:

Error: Can't combine `..1$order` <character> and `..2$order` <integer>.

It sounds like in one of the files the order column is being read in as a character. Could you check on the updated file(s) order columns to make sure they are integers.

**Comment by heimannch** [comment]
Of course! Just updated the file.

**Comment by andrewelamb** [comment]
@heimannch Could you check to see if you are seeing the updated?

**Comment by heimannch** [comment]
Yes, colors were updated!
