### ISSUE TITLE
Create nanostring data query

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#211]
Acceptance criteria
- [Add data to database ](https://gitlab.com/cri-iatlas/iatlas-data/-/issues/24)
- [Create a query in the API that returns nanostring data instead of bulk RNASeq.](https://gitlab.com/cri-iatlas/iatlas-api/-/issues/57)
- [Add a function in the client that does this query.](https://github.com/CRI-iAtlas/iatlasGraphqlClient_old/issues/56)
- Update app to use new api client library

**Comment by milen-sage** [comment]
@andrewelamb is the last step in this issue resolved via [this PR](https://github.com/CRI-iAtlas/iatlasGraphQLClient/pull/4)?

**Comment by andrewelamb** [comment]
Yes!
