### ISSUE TITLE
Inconsistencies in Responder/Progression/Clinical_Benefit annotations

### ISSUE THREAD

**Issue by jaeddy** [CRI-iAtlas/iatlas-app#214]
Opening this issue on behalf of Aik Choon Tan at the Moffitt Cancer Center:

> Thanks for developing the useful CRI iAtlas web portal, and also recently adding the new data sets on immunotherapy in the portal.
>
> However, recently, when we tried to download the data [iatlas-ici-features.tsv](https://www.synapse.org/#!Synapse:syn26560788) from Synapse, we noticed that some data sets have the Responder/Progression/Clinical_Benefit labels flipped. For example, if you look at the Riaz data set, Riaz_Nivolumab_2017-p001-ar-8813 has a response “Progressive Disease”, however the Responder column is flagged as “TRUE”, and the “Progression” column is also flagged as “TRUE”, and the Clinical_Benefit is flagged as “FALSE”. Similarly, if you look at the Riaz_Nivolumab_2017-p001-ar-8877, which is a “Partial Response”, the Responder column is flagged as “FALSE” and the Progression is also flagged as “FALSE”. There are some samples in VanAllen, as well as the IMvigro and IMmotion.

![image](https://user-images.githubusercontent.com/5033229/166126647-9405f61e-8065-44b5-a8f7-c5c79ec46979.png) 

> In addition, in the iAtlas page, the definition of “Responder” is PR or CR, and “Non-Responders” are SD or PD. But if you look at the Riaz_Nivolumab_2017-p001-ar-8815, the Clinical_Benefit column is flagged as “TRUE”.
 
![image](https://user-images.githubusercontent.com/5033229/166126655-90a1825b-abef-4fcf-ad6d-84a95dfb56ab.png)

> I think this a great resource to the community, and it will be helpful to provide the correct labels for researchers to download and do their analyses.
> 
> Thanks again for your great product! Happy to discuss more if needed.

**Comment by andrewelamb** [comment]
@heimannch This is the fix you made to the database last week correct?

@jaeddy If so, once the database rebuilds this will be fixed.

**Comment by heimannch** [comment]
Yes! And I also already updated the [iatlas-ici-features.tsv](https://www.synapse.org/#!Synapse:syn26560788) file on Synapse.

**Comment by ychae** [comment]
Waiting on the deployment fix from Xa and Jon

**Comment by milen-sage** [comment]
What is the status on this? And what's the AC?

**Comment by ychae** [comment]
The bug has been fixed but we're stuck on deploying the fix until the database build issue has been resolved (Xa is working on this with Jon from GenUI)

**Comment by ychae** [comment]
AC: Update the [iatlas-ici-features.tsv](https://www.synapse.org/#!Synapse:syn26560788) to reflect the correct responder information (some labels are flipped) and deploy the fix to the live production app.

**Comment by heimannch** [comment]
FYI: [iatlas-ici-features.tsv](https://www.synapse.org/#!Synapse:syn26560788) is already updated with the correct version.

**Comment by ychae** [comment]
Blocker: Database build issue has not been resolved. I've reached out to Sage IT and GenUI as couple times about this (including today) but haven't heard anything. @jaeddy would you be able to help us escalate this? 

moving this to our backlog until the DB build issue is resolved.
