### ISSUE TITLE
Update R,BioC, packages

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#220]
R needs to be updated to 4.2 and Bioconductor need to be updated to 3.15.

**Comment by heimannch** [comment]
I was able to install cyjShiny, igvShiny and their dependencies - app runs locally with no issues, and it deployed to testing. However, when accessing the modules that use these packages, error message appears and the logs show that the app is not finding the packages: 
```
2022-05-23T16:23:43.284886+00:00 shinyapps[5749838]: Warning: Error in loadNamespace: there is no package called ‘cyjShiny’
2022-05-23T16:23:50.284892+00:00 shinyapps[5749838]: Warning: Error in loadNamespace: there is no package called ‘igvShiny’
``

**Comment by heimannch** [comment]
After some changes in the DESCRIPTION file, both libraries work, but only the first one that is opened. If I go first to Germline Analysis, IGV works, then Extracellular network will not render the network - inverting the access order ends up with the opposite behavior.

I contacted the developer of cyjShiny and igvShiny to check if he has an idea of what might be happening:
https://github.com/paul-shannon/igvShiny/issues/27

**Comment by heimannch** [comment]
The current version in `update_r2` is updated and was deployed.
