### ISSUE TITLE
ICI Datasets overview lists fewer datasets ICI than cohort selection

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#224]
The live app lists 12 datasets on Datasets Overview 

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/2837859/172722078-69fc5acb-0b57-4c0c-acee-bd5c54586e98.png">

ICI cohort selection has three more

<img width="526" alt="image" src="https://user-images.githubusercontent.com/2837859/172722230-7fb1cd3d-41e8-4c90-963e-72ea09ad9c3a.png">

The three seem to be Chen 2016 , Melero 2019, Prat 2017

**Comment by vthorsson** [comment]
15 is also supported by this query 
```
ici_datasets <- iatlas.api.client::query_datasets(types = "ici")
```
as seen in ICI notebooks such as https://github.com/CRI-iAtlas/iatlas-notebooks/blob/main/ici_models_elastic_net.ipynb

**Comment by heimannch** [comment]
This is already taken care of in af1ea95106083a1ba2f51fdafbbf4aac2bab0c5d. The missing ones in the table are Nanostring datasets, table will be updated when the ui accommodating the nanostring datasets is merged.
