### ISSUE TITLE
metadata fields  "Sample_Treated" and "Sample_Treatment" 

### ISSUE THREAD

**Issue by gsiegwald** [CRI-iAtlas/iatlas-app#231]
Hi,

I understand from the readme uploaded on synapse that the field "Sample_treated" in the metadata of the CRI iAtlas cohort describes if the patient had been treated at the time the sample was taken.

I'm wondering what are the differences between "Sample_treated" and "Sample_treatment" columns.

Most samples are either "Samples_treated=TRUE and Sample_treatment=On", or "Samples_treated=False and Sample_treatment=Pre".

But there are few samples where "Samples_treated=TRUE and Sample_treatment=Pre", or "Samples_treated=False and Sample_treatment=On".

Thank you,

Guillaume

**Comment by heimannch** [comment]
Hello @gsiegwald,

The two annotations aim to differentiate the treatment with Immune Checkpoint Inhibitor and other types of therapy involved in a given study and annotated in the source material. In most of the cases the two overlap, but in the cases you mentioned, the studies had additional treatment information that created the observed combination.

- "Samples_treated=TRUE and Sample_treatment=Pre": they have undergone treatment (Samples_treated=TRUE), progressed, and had a sample collected before ICI therapy focus of the study (Sample_treatment=Pre). For more information: https://pubmed.ncbi.nlm.nih.gov/27169994/
- "Samples_treated=False and Sample_treatment=On": the Prins study aims to check the effectiveness of pembrolizumab as neoadjuvant, and samples with this combination had pembrolizumab as neoadjuvant (Sample_treatment=On) before surgery (Samples_treated=False) and sample collection. Please note that the neoadjuvant annotation is available in the NeoICI_Tx column. For more information: https://pubmed.ncbi.nlm.nih.gov/30742122/

Hope this clarifies!

**Comment by gsiegwald** [comment]
Hi Carolina,
Thank you very much for your explanation, it all makes sense now :)
