### ISSUE TITLE
gwas germline module broken in igvShiny version 1.5.1

### ISSUE THREAD

**Issue by wfulp** [CRI-iAtlas/iatlas-app#237]
The gwas germline tracks are currently broken in the iAtlas app. This is due to the version of igvShiny that's in the renv.lock file no longer working as expected.

In v1.5.1:
```
> igvShiny::parseAndValidateGenomeSpec(genomeName="hg19",  initialLocus="all")

Error in igvShiny::parseAndValidateGenomeSpec(genomeName = "hg19", initialLocus = "all") : 
  Your genome 'hg19' is not currently supported
Currently supported: 
```

However in the current version on Github (v1.5.9005) it works as intended, and works how it used to work in this package/app. I think this is due to a change in the json file it read that broke the old code in v1.5.1.

```
> igvShiny::parseAndValidateGenomeSpec(genomeName="hg19",  initialLocus="all")
$stockGenome
[1] TRUE

$dataMode
[1] NA

$validated
[1] TRUE

$genomeName
[1] "hg19"

$initialLocus
[1] "all"

$fasta
[1] NA

$fastaIndex
[1] NA

$annotation
[1] NA
```

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/12237512/218205729-5303cc27-3990-4119-b176-1bad7cc2cb41.png)

**Comment by heimannch** [comment]
Hi @wfulp. 
Thanks for reaching out and using iAtlas! This issue has been fixed, you should be able to see the IGV plot in the Germline Analysis module.

**Comment by wfulp** [comment]
> Hi @wfulp. 
> 
> Thanks for reaching out and using iAtlas! This issue has been fixed, you should be able to see the IGV plot in the Germline Analysis module.

Thanks. The germline module is working great now.
