### ISSUE TITLE
error when starting from docker env

### ISSUE THREAD

**Issue by Gibbsdavidl** [CRI-iAtlas/iatlas-app#248]
Working from the [docker_env](https://github.com/CRI-iAtlas/iatlas-app/tree/docker_env) branch.

After checking out the branch, the docker image can be build using 
`docker compose build`

and then we can log into the docker image with
`docker run -p 3838:3838 -it iatlas-app-shiny-app bash`

then to start R without triggering renv
`R --vanilla`

inside R, we can source 'init.R', which is the same as just calling 
`devtools::load_all('.')`

and if we run `> search()`, we can see that 'iatlas.app' is in the namespace.

Then to start the app, I'm running
`shiny::runApp(appDir='.', port=3838, host="0.0.0.0", launch.browser = FALSE)`

In the browser, if you point to `http://0.0.0.0:3838`, the app does appear to load, but then
crashes, and an error is returned:

```
Listening on http://0.0.0.0:3838
Warning: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
Warning: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
Warning: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
Warning: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
Warning: Navigation containers expect a collection of `bslib::nav()`/`shiny::tabPanel()`s and/or `bslib::nav_menu()`/`shiny::navbarMenu()`s. Consider using `header` or `footer` if you wish to place content above (or below) every panel's contents.
Warning: Error in : 'call_iatlas_module' is not an exported object from 'namespace:iatlas.app'

  43: as_mapper [/tmp/Rtmpv7s0eY/R.INSTALLbc2060068761/purrr/R/pmap.R#148]
  42: pmap_ [/tmp/Rtmpv7s0eY/R.INSTALLbc2060068761/purrr/R/pmap.R#121]
  41: pmap [/tmp/Rtmpv7s0eY/R.INSTALLbc2060068761/purrr/R/pmap.R#78]
  40: purrr::pwalk [/tmp/Rtmpv7s0eY/R.INSTALLbc2060068761/purrr/R/pmap.R#148]
  39: %>% [/tmp/Rtmpp2EPoE/R.INSTALL29ca6bd880bc/magrittr/R/pipe.R#136]
  38: server [/home/iatlas-app/server.R#52]
   1: shiny::runApp [/tmp/RtmpayvY6w/R.INSTALL939d55e06b09/shiny/R/runapp.R#388]
Error : 'call_iatlas_module' is not an exported object from 'namespace:iatlas.app'
```

This function, 'call_iatlas_module' is defined in R/call_iatlas_module.R, but I'm not sure why it's not making it into the namespace.  sourcing ('call_iatlas_module.R') doesn't seem to help.

**Comment by heimannch** [comment]
I will try to reproduce the error - but just from the top of my head, why is it referring to "iatlas.app" and not "iatlas-app"?

**Comment by Gibbsdavidl** [comment]
Thank you!  Not sure!  I think that's from devtools::load_all

**Comment by heimannch** [comment]
@Gibbsdavidl, I removed all references to `iatlas.app` in the module and now it works. I have a recollection of @andrewelamb  mentioning that `iatlas-app` was initially organized as an R package, but for some reason it changed later.
Let me know if it works for you now!

**Comment by Gibbsdavidl** [comment]
Thank you!  So often it’s the smallest things!  Looking forward to trying
it out.

There’s a way to start it up with “docker compose watch” where changes in
the source files get immediately changed in the docker image, but I haven’t
figured it out yet.

David L Gibbs, PhD
Senior Research Scientist
Shmulevich Lab
Institute for Systems Biology
