### ISSUE TITLE
Patient demographics not available at cohort selection

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlas-app#249]
We cannot use demographics (age, gender, weight, height) in the cohort selection for filter or group samples.

**Comment by heimannch** [comment]
@andrewelamb, I'm not sure if this issue should be addressed with changes in the manifest files, API or cohort selection - do you have any thoughts? These variables are stored in the patients table, so I suspect that's why they are not showing up in the cohort selection.

**Comment by andrewelamb** [comment]
@heimannch Yeah thats a good question. You could add the numeric ones as features, and the others ones as tags (in the manifest files) that would probably be the easiest way of doing it.
