### ISSUE TITLE
Various adjustments to driver module 

### ISSUE THREAD

**Issue by vthorsson** [CRI-iAtlas/iatlas-app#44]
Comparison looks good to the reference (public app, shiny-iatlas). Suggestions

- Display number of tests, as done on shiny-iatlas
- Recommend that default minimums be 3, 1 and respectively instead of 20,20
- plotly main title (top), tends to get sliced off
- for choice IFN-gamma response, response variable & Immune subtypes, the horizontal dotted line does not extend far enough to left
- Choice Th1 Cells & Immune Subtypes, no regression results available - needs investigation
- Violin plot: Show Wt to left, Mut to right

**Comment by andrewelamb** [comment]
@vthorsson "Recommend that default minimums be 3, 1" I think the test needs a minimum of 2 for each group.

**Comment by andrewelamb** [comment]
@vthorsson "Choice Th1 Cells & Immune Subtypes, no regression results available" you are right, these results aren't in the database ATM. These may have gotten lost in the translation from the old files to database process. I'll make re-runing these with the new workflow a priority.

This is more of a data issue so I started a new issue  [here](https://gitlab.com/cri-iatlas/iatlas-data/-/issues/11)

**Comment by andrewelamb** [comment]
@vthorsson  "plotly main title (top), tends to get sliced off" This is a known plotly issue, that effects a few of our plots. I've tried to fix this in several apps without much success.

**Comment by vthorsson** [comment]
Thanks for comments above @andrewelamb 

Regarding the minimal counts threshold and testable relationships, for comparison, on  shiny-iatlas we have 
```
get_testable_mutation_groups <- function(df, count_threshold = 4){
    df %>%
        dplyr::filter(mutation_count >= count_threshold) %>% # requirement for a minimal mutation count
        dplyr::filter(mutation_count < cat_count - 1) %>% # cannot test if all mutated or all but one mutated
        magrittr::use_series(mutation_group)
}
```

**Comment by andrewelamb** [comment]
@vthorsson I've started a separate issue for the plotly title, as that seems to happen in several plots:
https://github.com/CRI-iAtlas/iatlas-app/issues/54
