### ISSUE TITLE
Survminer throwing warnings.

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#52]
@vthorsson @Gibbsdavidl 
The clinical outcomes survival plot:

create_kmplot <- function(fit, df, confint, risktable, title, group_colors) {
    survminer::ggsurvplot(
        fit,
        data = df,
        conf.int = confint,
        risk.table = risktable,
        title = title,
        palette = group_colors
    )
}
survminer hasn't had any updates since July, it's not clear if anyone is working on it. We're getting a warning with the latest version of ggplot2:

https://github.com/kassambara/survminer/issues/455

The plots seem to be fine for now, but we may have to find another survival plot in the future if this repo is abandoned.

**Comment by kassambara** [comment]
This issue is fixed now by the merged pull request https://github.com/kassambara/survminer/pull/503 in the survminer dev version

**Comment by andrewelamb** [comment]
Thanks @kassambara!
