### ISSUE TITLE
Look into replacement for cyjShiny

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#60]
The cyjShiny package doesn't seem to have been updated since Aug 14, 2018. In addition I'm having trouble getting it installed in the test environment due like to a malformed description file: https://github.com/cytoscape/cyjShiny/blob/master/DESCRIPTION

I've removed cyjShiny from our description file which solves the test environment issue, but if we ever move away from shinyapps.io it could be come a problem in future deployments.

**Comment by vthorsson** [comment]
@heimannch , you had the latest info on installation modes.  We could also contact the software author with requests if needed!

**Comment by andrewelamb** [comment]
@vthorsson @heimannch  We are now using this fork:

https://github.com/CRI-iAtlas/cyjShiny

The only modification is this file:

https://github.com/CRI-iAtlas/cyjShiny/blob/master/DESCRIPTION
