### ISSUE TITLE
Cellimage Illustration working locally, but not in shinyapps.io

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#65]
The cellimage module is online at: https://isb-cgc.shinyapps.io/iatlas-v2-staging/

The cell illustration works locally, but not in shinapps.io getting this error:

Error: An error has occurred. Check your logs or contact the app author for clarification.

**Comment by heimannch** [comment]
From the logs at shinyapps.io:

`Warning: Error in loadNamespace: there is no package called ‘grImport2’`

**Comment by andrewelamb** [comment]
I added that to the description, that fixed it!
