### ISSUE TITLE
Cellimage Illustration not loking correct

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#67]
The Cellimage illustration has some issues vs how it looks in v1.3

- Cell nucleii color not correct
- CD155 protein is black not green
- text has poor resolution

**Comment by vthorsson** [comment]
Things to look into: From load_data.R, do `cellimage_base <- load_cellimage_base()` (possibly need to extract cellimage_base down one layer in object returned). Inspect things like `image_grob`   and `pathlabels`  in that object and compare with 1.3.

Be aware that `pathlabels[1:44]` may have been edited to `pathlabels[1:43]` in `functions/cellimage.utils.R`  to get the module to display an image.

**Comment by vthorsson** [comment]
A possible shift may have happened in updates of `grid` and `grImport2` pages. [grImport2](https://cran.r-project.org/web/packages/grImport2/index.html) has however not been updated this year.

**Comment by vthorsson** [comment]
From @andrewelamb : The branch you'll want to look in is: https://github.com/CRI-iAtlas/iatlas-app/tree/mv_cellimage_module_to_api

**Comment by vthorsson** [comment]
Turned out main issue was the CD 8 T cell entry was missing from the file containing image objects labels.  Has been corrected, on the above branch

**Comment by andrewelamb** [comment]
@vthorsson 

https://isb-cgc.shinyapps.io/iatlas-v2-staging/ has these updates. It looks like the text resolution isn't as sharp as before. I'll leave it to you if you want to re-open this issue.
