### ISSUE TITLE
Add IO targets updates from 1.3.1

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#72]

**Comment by vthorsson** [comment]
See
https://github.com/CRI-iAtlas/shiny-iatlas/issues/200

Also, before closing this issue, ensure that https://github.com/CRI-iAtlas/iatlas-app/issues/42 was addressed

**Comment by vthorsson** [comment]
File to be replaced is at 
https://www.synapse.org/#!Synapse:syn22151533
Task: look at format at of that and compare with corresponding new file in `shiny-iatlas/data/io_target_annotations.feather`

**Comment by vthorsson** [comment]
@andrewelamb , as the file format of `shiny-iatlas/data/io_target_annotations.feather` (version 1.3.1 data update) looks identical to that currently on https://www.synapse.org/#!Synapse:syn22151533, I have simply updated the latter with a new version (synapse Version 2 of file, md5 f782a73a12c0a78b4d56c230f6248d2c).  Please let me know if anything else is needed

**Comment by andrewelamb** [comment]
@vthorsson   These have duplicate entries per entrez id:
`
# Groups:   Entrez ID [4]
  Gene   `HGNC Symbol` `Friendly Name` `Entrez ID` Pathway   `Therapy Type`  Description    IO_target_URL    count
  <chr>  <chr>         <chr>           <chr>       <chr>     <chr>           <chr>          <chr>            <int>
1 HSP90… HSP90B1       BTE6-LX-8b      7184        Toll-lik… Targeted by Ot… Peptides deri… https://www.can…     3
2 HSP90… HSP90B1       BTE6-X-15-7     7184        Toll-lik… Targeted by Ot… Peptides deri… https://www.can…     3
3 FCGR3… FCGR3A        CD16            2214        Compleme… Other immunomo… CD16 has two … https://www.can…     2
4 FCGR3… FCGR3A        CD16a           2214        Compleme… Other immunomo… CD16a is one … https://www.can…     2
5 CD3E … CD3E          CD3E            916         T-Cell a… T-cell targete… CD3 is the ma… https://www.can…     2
6 CD3E … CD3E          CD3E            916         T-Cell a… T-cell targete… CD3E is part … https://www.can…     2
7 EGFR … EGFR          EGFR            1956        EGF-EGFR… Targeted by Ot… EGFR is the r… https://www.can…     2
8 EGFR … EGFR          EGFRvIII        1956        EGF-EGFR… Targeted by Ot… EGFRvIII is a… NA                   2
9 HSP90… HSP90B1       HSP90B1         7184        Focal Ad… Targeted by Ot… Gp96 is a cha… https://www.can…     3
`

**Comment by vthorsson** [comment]
I think that de-duplicating by retaining the first entry should be OK in this case
```
io_target_annotations <- feather::read_feather("data/io_target_annotations.feather")
io_target_annotations_new <- io_target_annotations[!duplicated(io_target_annotations$`Entrez ID`),]
io_target_annotations <- io_target_annotations_new
feather::write_feather(io_target_annotations,"data/io_target_annotations.feather")
```

New version, 3,  uploaded to  https://www.synapse.org/#!Synapse:syn22151533 , md5 a3ca2ca0b156574dab5de5b8fe2b9bdf

**Comment by andrewelamb** [comment]
@vthorsson The database will reflect this change next time it gets rebuilt.
