### ISSUE TITLE
Extracellular network Selectize causing warnings

### ISSUE THREAD

**Issue by andrewelamb** [CRI-iAtlas/iatlas-app#87]
@heimannch Could you look into implementing this?

Warning (test-extracellular_network_main_server.R:133:3): extracellular_network_main_server_tcga_study_with_stratification
The select input "proxy1-selected_genes" contains a large number of options; consider using server-side selectize for massively improved performance. See the Details section of the ?selectizeInput help topic.
Backtrace:
   1. shiny::testServer(...) test-extracellular_network_main_server.R:133:2
  26. shiny:::`$.shinyoutput`(output, stratify_ui)
  27. .subset2(x, "impl")$getOutput(name)
  28. shiny:::flushReact()
  29. private$flush()
  30. shiny:::flushReact()
  31. .getReactiveEnvironment()$flush()
  32. ctx$executeFlushCallbacks()
  33. base::lapply(...)
  34. shiny:::FUN(X[[i]], ...)
      ...
  65. shiny:::`<observer>`(...)
  74. shiny:::func(self, name)
  75. shiny:::renderFunc(...)
  88. shiny:::func()
  89. iatlas.app:::renderUI(...)
  90. shiny::selectizeInput(...) /home/alamb/repos/iatlas-app/R/extracellular_network_main_server.R:106:8
  95. shiny::selectInput(inputId, ..., selectize = FALSE, width = width)
  98. shiny:::selectOptions(choices, selected, inputId, selectize)
  99. base::mapply(...)
 102. shiny:::selectOptions(choice, selected, inputId, perfWarning)
──────────────────────────────────────────────────────────────────────────

**Comment by heimannch** [comment]
@andrewelamb, I just submitted a PR with this adjustment + a few minor fixes in the extracellular network module.
I also noted that the network score results seem to be the same for PCAWG and TCGA, but I understand that we only have results for TCGA? (I would be glad to open a separate issue, in case this is something that needs to be tracked)

**Comment by andrewelamb** [comment]
@heimannch Would you create an issue, with an example of what you are seeing?

**Comment by heimannch** [comment]
Sure, just opened #91. I will close this issue.
