### ISSUE TITLE
Extracellular network data the same for PCAWG and TCGA

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlas-app#91]
How to reproduce the issue:
1. launch the app
2. go to Extracellular Network (default dataset option is PCAWG), hit the "GO" button and export the node and edge tables
3. go to Cohort Selection and change dataset to TCGA
4. Repeat step 2

The node and edges tables from TCGA and PCAWG (and the network displayed) are the same.

**Comment by heimannch** [comment]
@andrewelamb, following up on my comment on #94 , here it goes what I think is causing all nodes in the network to be blue when dataset = PCAWG.

`filtered_nodes()` table has Type = NA when dataset = PCAWG:
id | Type | Node | FriendlyName | Group | Abundance
-- | -- | -- | -- | -- | --
BTLA | NA | BTLA | BTLA | C2 | 0.8503937

For comparison, this is how the `filtered_nodes()` table looks like when dataset = TCGA:

id | Type | Node | FriendlyName | Group | Abundance
-- | -- | -- | -- | -- | --
CTLA4 | Receptor | CTLA4 | CTLA4 | C1 | 0.7374741

**Comment by andrewelamb** [comment]
@heimannch Could you create a separate issue for the missing PCAWG types?
