### ISSUE TITLE
Extracellular network query for PCAWG returns NA in Type annotation 

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlas-app#98]
Extracellular networks for dataset = PCAWG have all nodes colored in blue. 
The color of the nodes is based on the annotation in the `Type` column in the nodes data that is sent to the network constructor. 

I added a `browser()` statement in line 185 of `extracellular_network_main_server.R` and checked the content of `filtered_nodes()` dataframe. I've noticed that everything in the `Type` column is set to NA, which would explain the fact that the displayed network nodes are all in blue.

`filtered_nodes()` table has Type = NA when dataset = PCAWG:
id | Type | Node | FriendlyName | Group | Abundance
-- | -- | -- | -- | -- | --
BTLA | NA | BTLA | BTLA | C2 | 0.8503937

For comparison, this is how the `filtered_nodes()` table looks like when dataset = TCGA:

id | Type | Node | FriendlyName | Group | Abundance
-- | -- | -- | -- | -- | --
CTLA4 | Receptor | CTLA4 | CTLA4 | C1 | 0.7374741

**Comment by andrewelamb** [comment]
Thanks @heimannch 

This looks like the workflow I made isn't returning these values. I'll take a look when I do another pass through the workflows.
